### PR TITLE
Numbered panels for Fibonacci & Prime Clock Dividers, and a CV input Rotating Clock Divider

### PR DESCRIPTION
**Pull request by rossco255**
Added numbering to the outputs for the Fibonnaci Clock Divider and Prime Clock Divider .SVGs, as discussed [here.](https://github.com/JerrySievert/SynthKit/issues/8) In the same font and colour as the already present text.

Also added a modification of the Rotating Clock Divider, as I suggested [here.](https://github.com/JerrySievert/SynthKit/issues/3) It's based on the preexisting version, but rather than responding to triggers, the rotation is based on CV input. Did so using some code from Michael Hetricks [Rotator](https://github.com/mhetrick/hetrickcv/blob/master/src/Rotator.cpp) plugin. 0V to 1.5V is the default position, 1.5V to 2.5V is the second position, etc. up to 7.5V and above which is the final position. Unlike the original, this version "caps out" at the final position rather than rotating back to the start again, but with this version one can scan back down the positions in reverse order.

### CODE REVIEW

**Comment by h00g** [comment]
I like the SVG addition.
The rotating clock divider I have no opinion on.

**Comment by JerrySievert** [comment]
I'll take a look at this in a few hours, thanks!

**Comment by JerrySievert** [comment]
can you do me a favor and run `clang-format -style="{BasedOnStyle: llvm, IndentWidth: 2, AllowShortFunctionsOnASingleLine: None, KeepEmptyLinesAtTheStartOfBlocks: false}"` on the cpp/cpp files you added?  that will make sure you keep in the git logs, and I get to keep formatted source :)

thanks!

**Comment by rossco255** [comment]
That should be formatted correctly now!

**Comment by JerrySievert** [comment]
looks good, thanks!

going to merge.

a couple of notes:

1) I'm going to change the name of the new clock divider to Rotating Clock Divider CV, and add it to the README
2) these changes will go out with the 0.6.0 release, which will only work with Rack 0.6.0, which is due very soon from what I understand - not going to back port the changes, since there were significant enough changes
3) I'm moving all custom components into their own repo, so if you update your source, make sure you run `git submodule update --remote` to get the new dependencies

it will take me a bit to get the new binaries compiled, since I need to update rack source and compile on all platforms, but should have something either today or tomorrow.

**Pull request merged**
